# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
# .travis_secrets.yaml

#homeassistant secrets:
latitude:         00.000000
longitude:        00.000000
elevation:        000

#http secrets:
base_url:         https://www.test.org:8123
http_password:    password
duck_dns_api:     1111111111111111111111
lifx_broadcast:   192.168.1.255

ifttt_api_key:    1111111111111111111111
pushbullet_api:   1111111111111111111111

# Lights Secrets:
vera_url:         http://192.168.1.4:3480/
philips_hue_ip:   192.168.1.5

# Camera still image access
# # ref in: include/cameras.yaml
cam_front_yard:   http://192.168.1.14/image/jpeg.cgi
cam_living_room:  http://192.168.1.13/image/jpeg.cgi
cam_back_door:    http://192.168.1.12/image/jpeg.cgi
cam_front_door:   http://192.168.1.11/image/jpeg.cgi

# Media Player secrets
# ref in: includes/media_players.yaml
samsung_tv_ip: 192.168.1.10
cast_ip_1:     192.168.1.62
cast_ip_2:     192.168.1.63
harmony_name:  harmony
harmony_host:  192.168.1.60

# Netatmo Weather Station
# ref in: configuration.yaml
netatmo_api_key:    1111111111111111111111
netatmo_secret_key: 1111111111111111111111
netatmo_username:   email@company.com
netatmo_password:   password

# Rachio irrigation API
# ref in: include/rachio.yaml
rachio_api_key:     1111111111111111111111

# Weblinks
# ref in: include/weblink.yaml
unifi_url:           www.website.com
weblink_plex_server: 192.168.1.5:32400/web/index.html

# Unifi - Ubiquiti login info
# ref in: include/device_trackers.yaml
unifi_host: 192.168.1.1
unifi_port: 22
unifi_username: user
unifi_password: password
unifi_site_id:  site

# Google Assistant secrets
# ref in: includes/google_assistant.yaml
ga_project_id:  project-id
ga_client_id:   long-string
ga_token:       this-is-a-token
ga_user:        user
ga_api:         api-key